services:

  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=app
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=192.168.42.76
    networks:
      - express-app

networks:
  express-app: